### ISSUE TITLE
How to hack Android to get USSDs in newer Android versions?

### ISSUE THREAD

**Issue by pligor** [alaasalman/ussdinterceptor#2]
Based on this line:
_“The rights of root are necessary for the program for processing of USSD answers to Android 4.2.2 above_ - https://play.google.com/store/apps/details?id=com.mdnsoft.ussddualwidgetpro

and this line: _It wont work with 4.2.2 due to security restrictions(changes have been made to PhoneApp code)_ - http://stackoverflow.com/questions/5477597/how-is-it-possible-to-do-ussd-requests-on-android

4.2.2 and after are not supporting apps which can handle USSDs

Is there any way to circumvent that? Any hackerish way would be acceptable.
Because an app can get very useful information from USSD responses

Thank you

**Comment by alaasalman** [comment]
There's no way to do it as far as I know.
